apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: pet-clinic-db
type: Opaque
stringData:
  username: petclinic
  password: petclinic
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: pet-clinic-app
type: Opaque
stringData:
  username: petclinic
  password: petclinic
