apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: secret-demo
spec:
  selector: {matchLabels: {app: mongo}}
  template:
    metadata: {labels: {app: mongo}}
    spec:
      containers:
      - name: mongo
        image: mongo:7
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: k8sExercice
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: k8sExercice
        ports: [{containerPort: 27017}]
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
        persistentVolumeClaim: {claimName: mongo-data}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: secret-demo
spec:
  selector: {app: mongo}
  ports: [{port: 27017, targetPort: 27017}]
