apiVersion: v1
kind: Secret
metadata:
  name: mongo
  namespace: secret-demo
type: Opaque
stringData:
  mongo_url: mongodb://k8sExercice:k8sExercice@mongo.secret-demo.svc.cluster.local:27017/message?authSource=admin
